# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       partnerspaces

# >> macros
BuildArch: noarch
# << macros

Summary:    A set of partner-spaces for SailfishOS
Version:    0.0
Release:    1
Group:      Qt/Qt
License:    TODO
URL:        https://github.com/sailfishos-patches/partnerspaces
Source0:    %{name}-%{version}.tar.bz2
Source100:  partnerspaces.yaml

%description
This package contains a set of partnerspaces.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/partnerspacemanager/partnerspaces
for f in $(ls maintained); do
cp -r maintained/$f %{buildroot}/usr/share/partnerspacemanager/partnerspaces/$f
done
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/partnerspacemanager/partnerspaces
# >> files
# << files
